name: Infrastructure Security Scan

on:
  workflow_call:
    outputs:
      scan-result:
        description: "IaC scan result"
        value: ${{ jobs.iac-scan.outputs.result }}

jobs:
  # 🚧 REPLACE THIS ENTIRE 'jobs:' SECTION WITH WORKSHOP CONTENT! 🚧
  # Copy from: workshop/iac_scan/{tool}/workflow.yml

  iac-scan:
    name: "🚧 IAC Scan - Workshop Placeholder"
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.placeholder.outputs.result }}
    steps:
      - name: Workshop Placeholder
        id: placeholder
        run: |
          echo "🚧 Replace this job with content from workshop/iac_scan/{tool}/workflow.yml!"
          echo "This will implement: Infrastructure security scan with your chosen tool"
          echo "result=workshop-placeholder" >> "$GITHUB_OUTPUT"