name: Pipeline Security Scan

on:
  workflow_call:
    outputs:
      scan-result:
        description: "Pipeline scan result"
        value: ${{ jobs.repository-scan.outputs.result }}

jobs:
  repository-scan:
    name: Repository Scan with Prowler
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.scan-result.outputs.result }}
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Install Prowler
        run: |
            # TODO: Installing from commit until 5.10 is released
            pipx install git+https://github.com/prowler-cloud/prowler.git@8dc4bd0be8e06464f6600ee68e368cadde7c7f22
            prowler -v

      - name: Run Prowler
        id: prowler
        # env:
        #   GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PAT }}
        run: |
            prowler github --repository {{ github.repository }} --personal-access-token ${{ secrets.GH_PAT }} --output-formats html
        continue-on-error: true

      - name: Message
        run: |
            echo "Prowler run completed"

      - name: Upload Prowler HTML Report
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: always()
        with:
          name: prowler-html-report
          path: output/*.html
          retention-days: 1

      - name: Set scan result
        id: scan-result
        if: always()
        run: |
          if [ "${{ steps.prowler.outcome }}" == "success" ]; then
            echo "result=success" >> "$GITHUB_OUTPUT"
            echo "✅ Pipeline scan passed"
          else
            echo "result=failure" >> "$GITHUB_OUTPUT"
            echo "❌ Pipeline scan failed"
          fi
